--liquibase formatted sql

--changeset denis:1

CREATE TABLE IF NOT EXISTS customer (  -- Таблица: Пользователь
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,          -- уникальный id
chat_id BIGINT NOT NULL,    -- id Telegram чата
surname VARCHAR(25) , -- фамилия
name VARCHAR(25),    -- имя
second_name VARCHAR(25), -- отчество
phone VARCHAR(12),       -- тлф формата +70000000000
address TEXT,             -- адрес
email VARCHAR(30)        -- почта клиента
);

CREATE TABLE IF NOT EXISTS pets (    -- Таблица: Приют
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age INTEGER NOT NULL,                         -- возраст питомца
    name          VARCHAR(20),                    -- имя питомца
    type_pets     VARCHAR(20),                    -- тип животного
    breed         VARCHAR(20),                    -- порода
    id_customer   BIGINT references customer,
    id_shelter    BIGINT references shelters
);

CREATE TABLE IF NOT EXISTS shelters ( -- Таблица: приют
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(20),                    -- имя приюта (совпадает с type_pets из таблицы pets)
    adress  VARCHAR(255),                   -- адрес прита
    location POINT NOT NULL                 -- координаты приюта
);