--liquibase formatted sq
--changeset marat:1

create table if not exists customer (  -- Таблица: Пользователь
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,          -- уникальный id
chat_id BIGINT NOT NULL,    -- id Telegram чата
surname VARCHAR(25) , -- фамилия
name VARCHAR(25),    -- имя
second_name VARCHAR(25), -- отчество
phone VARCHAR(12),       -- тлф формата +70000000000
address TEXT,             -- адрес
email VARCHAR(30)        -- почта клиента
);

create table if not exists shelters ( -- Таблица: приют
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(20),                    -- имя приюта (совпадает с type_pets из таблицы pets)
    adress  VARCHAR(255),                   -- адрес приюта
   location VARCHAR(100) NOT NULL          -- координаты приюта

);
create table if not exists pets (    -- Таблица: Приют
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age INTEGER NOT NULL,                         -- возраст питомца
    name          VARCHAR(20),                    -- имя питомца
    type_pets     VARCHAR(20),                    -- тип животного
    breed         VARCHAR(20),                    -- порода
    id_customer   BIGINT references customer,
    id_shelter    BIGINT references shelters
);
create table if not exists volunteer
(
    id          bigint generated by default as identity primary key,
    adress      varchar(255),
    chat_id     bigint not null,
    name        varchar(255),
    phone       varchar(255),
    second_name varchar(255),
    surname     varchar(255)
);

create table if not exists volunteer    -- Таблица: волонтеров
(
    id          bigint generated by default as identity
    primary key,
    sex         varchar(20),            -- пол волонтера
    chat_id     bigint not null,        -- id чата волонтера
    name        varchar(30),
    phone       varchar(20),
    second_name varchar(30),
    surname     varchar(30)
    );
--changeset denis:2
ALTER TABLE shelters ALTER COLUMN location type VARCHAR(255);
--changeset denis:3
ALTER TABLE volunteer ADD COLUMN if not exists id_shelter BIGINT references shelters;
--changeset denis:4
update DATABASECHANGELOG set md5sum = null where true;
--changeset denis:5
create table if not exists report    -- Таблица: отчета
(
    id          bigint generated by default as identity
        primary key,
    petReport    varchar(255),         -- краткий отчет
    date        DATE,                  -- дата сдачи отчета
    id_pets   BIGINT references pets
);
--changeset denis:6
create table if not exists photoPet    -- Таблица: фотоотчета
(

    id          bigint generated by default as identity
        primary key,
    filePath     varchar(255),
    fileSize     BIGINT,
    mediaType    varchar(255),
    id_pets   BIGINT references pets
);

--changeset denis:7
ALTER TABLE customer ADD CONSTRAINT chat_id_unique UNIQUE (chat_id);

--changeset denis:8
update DATABASECHANGELOG set md5sum = null where true;