--liquibase formatted sq
--changeset marat:1

create table if not exists customer (  -- Таблица: Пользователь
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,          -- уникальный id
chat_id BIGINT NOT NULL,    -- id Telegram чата
surname VARCHAR(25) , -- фамилия
name VARCHAR(25),    -- имя
second_name VARCHAR(25), -- отчество
phone VARCHAR(12),       -- тлф формата +70000000000
address TEXT,             -- адрес
email VARCHAR(30)        -- почта клиента
);

create table if not exists shelters ( -- Таблица: приют
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(20),                    -- имя приюта (совпадает с type_pets из таблицы pets)
    adress  VARCHAR(255),                   -- адрес приюта
   location VARCHAR(100) NOT NULL          -- координаты приюта

);
create table if not exists pets (    -- Таблица: Приют
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age INTEGER NOT NULL,                         -- возраст питомца
    name          VARCHAR(20),                    -- имя питомца
    type_pets     VARCHAR(20),                    -- тип животного
    breed         VARCHAR(20),                    -- порода
    id_customer   BIGINT references customer,
    id_shelter    BIGINT references shelters
);
create table if not exists volunteer
(
    id          bigint generated by default as identity primary key,
    adress      varchar(255),
    chat_id     bigint not null,
    name        varchar(255),
    phone       varchar(255),
    second_name varchar(255),
    surname     varchar(255)
);

